/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import conectar.conex;

/**
 *
 * @author ASUS
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        sesion = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        campousuario = new javax.swing.JTextField();
        separar2 = new javax.swing.JSeparator();
        usuario = new javax.swing.JLabel();
        separar1 = new javax.swing.JSeparator();
        clave = new javax.swing.JTextField();
        ingresar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, -1));

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sesion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        sesion.setText("INICIAR SESIÓN");
        panel1.add(sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        contraseña.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        contraseña.setText("CONTRASEÑA");
        panel1.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        campousuario.setForeground(new java.awt.Color(153, 153, 153));
        campousuario.setText("Ingrese su nombre de usuario");
        campousuario.setBorder(null);
        campousuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campousuarioMousePressed(evt);
            }
        });
        panel1.add(campousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 319, 24));

        separar2.setBackground(new java.awt.Color(0, 0, 0));
        separar2.setForeground(new java.awt.Color(0, 0, 0));
        separar2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panel1.add(separar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 355, 10));

        usuario.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        usuario.setText("USUARIO");
        panel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        separar1.setBackground(new java.awt.Color(0, 0, 0));
        separar1.setForeground(new java.awt.Color(0, 0, 0));
        separar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panel1.add(separar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 355, 10));

        clave.setForeground(new java.awt.Color(153, 153, 153));
        clave.setText("Ingrese su contraseña");
        clave.setBorder(null);
        clave.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        clave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                claveMousePressed(evt);
            }
        });
        clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveActionPerformed(evt);
            }
        });
        panel1.add(clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 336, 340, 20));

        ingresar.setBackground(new java.awt.Color(110, 42, 42));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("INGRESAR");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ingresarLayout = new javax.swing.GroupLayout(ingresar);
        ingresar.setLayout(ingresarLayout);
        ingresarLayout.setHorizontalGroup(
            ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        ingresarLayout.setVerticalGroup(
            ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panel1.add(ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 110, 40));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 450, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claveActionPerformed

    private void campousuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campousuarioMousePressed
     if(campousuario.getText().equals("Ingrese su nombre de usuario")){
        campousuario.setText("");
      campousuario.setForeground(Color.black);
     }
     if(clave.getText().isEmpty()){
clave.setText("Ingrese su contraseña");
     clave.setForeground(Color.gray);
     }
    }//GEN-LAST:event_campousuarioMousePressed

    private void claveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_claveMousePressed
      if(clave.getText().equals("Ingrese su contraseña")){
        clave.setText("");
     clave.setForeground(Color.black);
}
      if(campousuario.getText().isEmpty()){  
      campousuario.setText("Ingrese su nombre de usuario");
     campousuario.setForeground(Color.gray);
    }
    }//GEN-LAST:event_claveMousePressed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        
       
        try {
            String nombre = campousuario.getText();
            String contraseña = clave.getText();
            
            conex con = new conex("postgres", "12345", "localhost", "5432", "cafeteria");
            con.ConexionPostgres();
            
            String query = "SELECT * FROM usuario WHERE nombre = '"+nombre+"' AND contraseña = '"+contraseña+"' ";
            
            ResultSet rs = con.consultar(query);
            if(rs.next()){
                if(nombre.equals("kerly")){
                    new Principal2().setVisible(true);
                }else if(nombre.equals("belsi")){
                    new Principal().setVisible(true);
                }
                
            }
            
            con.cerrar();
        } catch (SQLException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campousuario;
    private javax.swing.JTextField clave;
    private javax.swing.JLabel contraseña;
    private javax.swing.JPanel ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panel1;
    private javax.swing.JSeparator separar1;
    private javax.swing.JSeparator separar2;
    private javax.swing.JLabel sesion;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
