/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import conectar.conex;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.sql.Types;
import java.sql.Array;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SENA
 */
public class product extends javax.swing.JPanel {
     public static String cad="", cad1="";
    Vector<Integer> vector = new Vector<>();
     DefaultTableModel dt= new DefaultTableModel();
      DefaultTableModel di= new DefaultTableModel();
      DefaultTableModel dl= new DefaultTableModel();
      
    /**
     * Creates new form product
     */
    public product() {
        initComponents();
        String ids[]={"ID ingrediente","Nombre"};
        di.setColumnIdentifiers(ids);
        mingre.setModel(di);
        
        String id[]={"ID ingrediente","Nombre","Descripción","Valor nutricional"};
        dt.setColumnIdentifiers(id);
        mostrar.setModel(dt);
        
         String idl[]={"ID Producto","Nombre","Id_familia","Descripción","Precio"};
        dl.setColumnIdentifiers(idl);
        listar.setModel(dl);
         
         try{
    conex con = new conex("postgres","12345","localhost","5432","cafeteria");
    con.ConexionPostgres();
    
    String query= "SELECT * FROM ingrediente order by nombre_ingrediente ASC";
    ResultSet rs= con.consultar(query);
           
    while(rs.next())
            {
             long id_ingre=(rs.getLong("id_ingrediente"));
             
            idingre.addItem(id_ingre+"-"+ rs.getString("nombre_ingrediente"));
            };
 
        } catch (Exception r) {
            r.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al conectar");
        }
    
    
    try{
    conex con = new conex("postgres","12345","localhost","5432","cafeteria");
    con.ConexionPostgres();
    
    String query= "SELECT * FROM familia order by nombre_familia ASC";
    ResultSet rs= con.consultar(query);
           
    while(rs.next())
            {
             long id_ingre=(rs.getLong("id_familia"));
             
            idfamilia.addItem(id_ingre+"-"+ rs.getString("nombre_familia"));
            };
 
        } catch (Exception r) {
            r.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al conectar");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        panelpro = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idproducto = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        existencia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        descripcion = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        idingre = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        mingre = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        idfamilia = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listar = new javax.swing.JTable();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        mostrar = new javax.swing.JTable();
        buscarid = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        stock = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();

        jPanel2.setBackground(new java.awt.Color(160, 52, 63));

        jLabel1.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingresar Ingredientes");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-ingredientes-50.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(472, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(14, 14, 14))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelpro.setBackground(new java.awt.Color(255, 255, 255));
        panelpro.setMinimumSize(new java.awt.Dimension(1024, 750));
        panelpro.setPreferredSize(new java.awt.Dimension(1024, 750));
        panelpro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(126, 44, 52));

        jLabel3.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingresar Productos");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-productos-50.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addContainerGap(942, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(14, 14, 14))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelpro.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 80));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Nombre Producto");
        panelpro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        idproducto.setBorder(null);
        panelpro.add(idproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 220, 30));
        panelpro.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 152, 210, 0));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("ID Producto");
        panelpro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        nombre.setBorder(null);
        panelpro.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 310, 30));
        panelpro.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 220, 10));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("ID Familia");
        panelpro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));
        panelpro.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 100, 10));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Existencia");
        panelpro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        existencia.setBorder(null);
        panelpro.add(existencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 100, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Descripción");
        panelpro.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        descripcion.setBorder(null);
        panelpro.add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 320, 30));
        panelpro.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 320, 10));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Precio ");
        panelpro.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        idingre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        idingre.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        idingre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        idingre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idingreActionPerformed(evt);
            }
        });
        panelpro.add(idingre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 190, 30));

        jPanel4.setBackground(new java.awt.Color(226, 226, 226));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-añadir-etiqueta-25.png"))); // NOI18N
        jPanel4.add(jLabel11);

        panelpro.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 30, 30));

        jPanel5.setBackground(new java.awt.Color(64, 23, 30));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-receptor-de-comida-30.png"))); // NOI18N
        jLabel12.setText("INSERTAR");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel12);

        panelpro.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 100, 40));
        panelpro.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 310, 10));
        panelpro.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 232, 290, 0));

        jSeparator15.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelpro.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 10, 630));

        jScrollPane1.setViewportView(mingre);

        panelpro.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 230, 110));

        jPanel9.setBackground(new java.awt.Color(64, 23, 30));
        jPanel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-actualizar-archivo-30.png"))); // NOI18N
        jLabel18.setText("MODIFICAR");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel9.add(jLabel18);

        panelpro.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 100, 40));

        idfamilia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        panelpro.add(idfamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 220, -1));

        jPanel1.setBackground(new java.awt.Color(234, 234, 234));
        jPanel1.setLayout(null);

        jScrollPane2.setViewportView(listar);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 50, 423, 140);
        jPanel1.add(jSeparator8);
        jSeparator8.setBounds(10, 30, 310, 30);

        jPanel10.setBackground(new java.awt.Color(64, 23, 30));
        jPanel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-editar-propiedad-30.png"))); // NOI18N
        jLabel19.setText("LISTAR");
        jPanel10.add(jLabel19);

        jPanel1.add(jPanel10);
        jPanel10.setBounds(340, 10, 90, 40);

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel20.setText("Productos registrados");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(10, 20, 170, 16);

        panelpro.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 450, 200));

        jPanel11.setBackground(new java.awt.Color(234, 234, 234));
        jPanel11.setLayout(null);

        jScrollPane3.setViewportView(mostrar);

        jPanel11.add(jScrollPane3);
        jScrollPane3.setBounds(10, 70, 430, 160);

        buscarid.setBackground(new java.awt.Color(234, 234, 234));
        buscarid.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buscarid.setForeground(new java.awt.Color(153, 153, 153));
        buscarid.setText("Ingrese Id del producto a buscar");
        buscarid.setBorder(null);
        buscarid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buscaridMousePressed(evt);
            }
        });
        buscarid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaridActionPerformed(evt);
            }
        });
        jPanel11.add(buscarid);
        buscarid.setBounds(10, 10, 320, 16);

        jPanel6.setBackground(new java.awt.Color(64, 23, 30));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(64, 23, 30));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-búsqueda-de-propiedad-30.png"))); // NOI18N
        jLabel13.setText("BUSCAR");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel13);

        jPanel11.add(jPanel6);
        jPanel6.setBounds(350, 10, 90, 40);

        jSeparator9.setBackground(new java.awt.Color(102, 102, 102));
        jPanel11.add(jSeparator9);
        jSeparator9.setBounds(10, 30, 310, 10);

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel15.setText("Ingredientes del producto");
        jPanel11.add(jLabel15);
        jLabel15.setBounds(10, 40, 140, 16);
        jPanel11.add(jSeparator16);
        jSeparator16.setBounds(10, 60, 440, 10);

        jPanel7.setBackground(new java.awt.Color(226, 226, 226));
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(226, 226, 226));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-borrar-fila-25.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel16))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)))
                .addGap(10, 10, 10))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(13, 13, 13))
        );

        jPanel11.add(jPanel7);
        jPanel7.setBounds(10, 230, 40, 30);

        jPanel8.setBackground(new java.awt.Color(226, 226, 226));
        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-actualizar-16.png"))); // NOI18N
        jPanel8.add(jLabel17);

        jPanel11.add(jPanel8);
        jPanel8.setBounds(50, 230, 40, 30);

        panelpro.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 450, 280));

        jLabel21.setFont(new java.awt.Font("MV Boli", 2, 12)); // NOI18N
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-cafe-100.png"))); // NOI18N
        panelpro.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 630, -1, -1));

        jLabel22.setFont(new java.awt.Font("Pristina", 1, 17)); // NOI18N
        jLabel22.setText("\"Energía, aroma y buena vibra en cada taza.\" ");
        panelpro.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 670, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("ID ingrediente");
        panelpro.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        precio.setBorder(null);
        panelpro.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 220, 30));
        panelpro.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 220, 10));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Stock Mínimo");
        panelpro.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        stock.setBorder(null);
        panelpro.add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 100, 30));
        panelpro.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 100, 10));

        add(panelpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
     
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
       
       String cod_ingre=(String)idingre.getSelectedItem();
       java.util.StringTokenizer st = new java.util.StringTokenizer(cod_ingre,"-");
       
       String token=st.nextToken();
       vector.add(Integer.valueOf(token));
       cad+=token+",";
       
       cad1=cad.substring(0,cad.length()-1);
      di.addRow(new Object[]{
          cod_ingre
      });
    }//GEN-LAST:event_jPanel4MouseClicked

    private void idingreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idingreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idingreActionPerformed

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        
      
    }//GEN-LAST:event_jPanel6MouseClicked

    private void buscaridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaridActionPerformed

    private void buscaridMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscaridMousePressed
      if(buscarid.getText().equals("Ingrese Id del producto a buscar")){
        buscarid.setText("");
      buscarid.setForeground(Color.black);
     }
      else{buscarid.getText().isEmpty();
buscarid.setText("Ingrese Id del producto a buscar");
     buscarid.setForeground(Color.gray);
     }
    }//GEN-LAST:event_buscaridMousePressed

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        DefaultTableModel modelo = (DefaultTableModel) mostrar.getModel();
        int filase= mostrar.getSelectedRow();
        
        if(filase !=-1){
            modelo.removeRow(filase);
        }else{JOptionPane.showMessageDialog(null,"Seleccione una fila para eliminar");}
        

    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        int bp= Integer.parseInt(buscarid.getText().trim());
        ArrayList<Integer> IngredientesID= new ArrayList<>();
        DefaultTableModel modelo = (DefaultTableModel) mostrar.getModel();
        for(int i=0; i<modelo.getRowCount();i++){
            IngredientesID.add(((Number)modelo.getValueAt(i, 0)).intValue());
        }
        
        Integer [] ingreArray= IngredientesID.toArray(new Integer[0]);
        try{
    conex con = new conex("postgres","12345","localhost","5432","cafeteria");
    con.ConexionPostgres();
      String query = "UPDATE producto SET id_ingrediente= ? WHERE id_producto=?";
    PreparedStatement ps = con.getConnection().prepareStatement(query);
    ps.setInt(2,bp );
    if(IngredientesID.isEmpty()){
        ps.setNull(1, Types.ARRAY);
    }else{
        Array sqlArray = con.getConnection().createArrayOf("integer", ingreArray);
        ps.setArray(1, sqlArray);
        int filasac= ps.executeUpdate();
        if(filasac>0){
            JOptionPane.showMessageDialog(null, "Base de datos actualizada");
        }
        
    }
        }   catch (SQLException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) { 
                Logger.getLogger(product.class.getName()).log(Level.SEVERE, null, ex);
            } 
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
       
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
      
      
        try{
    conex con = new conex("postgres","12345","localhost","5432","cafeteria");
    con.ConexionPostgres();
    
    String query= "SELECT * FROM producto";
    ResultSet rs= con.consultar(query);
    dl.setRowCount(0);
    while(rs.next())
    {
        dl.addRow(new Object[]{
        rs.getLong("id_producto"),
        rs.getString("nombre_producto"),
        rs.getString("id_familia_producto"),
        rs.getString("descripcion_producto"),
        rs.getInt("precio_producto"),
        rs.getInt("stock_producto"),
        rs.getInt("existencia_producto")
                });
    }
         } catch (Exception r) {
             r.printStackTrace();
             JOptionPane.showMessageDialog(null, "Error al listar");
         }
    }//GEN-LAST:event_jPanel10MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
   
        int id_prod=Integer.parseInt(idproducto.getText().trim());
     String nombrep=nombre.getText().trim();
     String id_fam= (String) idfamilia.getSelectedItem();
     String descrip=descripcion.getText().trim();
     double valor=Double.parseDouble(precio.getText());
     int stminimo = Integer.parseInt(stock.getText());
     int exist = Integer.parseInt(existencia.getText());
       try{
    conex con = new conex("postgres","12345","localhost","5432","cafeteria");
    con.ConexionPostgres();
      String query = "INSERT INTO producto VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
    PreparedStatement ps = con.getConnection().prepareStatement(query);
    ps.setInt(1, id_prod);
    ps.setString(2, nombrep);
    ps.setString(3, id_fam);
    ps.setString(4, descrip);
    ps.setDouble(5, valor);
    ps.setInt(6, stminimo);
    ps.setInt(7, exist);
    ps.setArray(8, con.getConnection().createArrayOf("integer", vector.toArray()));
    
    ps.executeUpdate();
    con.cerrar();
    
    idproducto.setText(""); nombre.setText(""); idfamilia.setSelectedIndex(-1); descripcion.setText(""); precio.setText(""); stock.setText(""); existencia.setText(""); idingre.setSelectedIndex(-1); dt.setRowCount(0);
       
       JOptionPane.showMessageDialog(null, "Producto insertado con exito");
               } catch (SQLException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
             Logger.getLogger(product.class.getName()).log(Level.SEVERE, null, ex);
         }       
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
         int id_prod = Integer.parseInt(buscarid.getText());
        dt.setRowCount(0 );
try {
   
    conex con = new conex("postgres", "12345", "localhost", "5432", "cafeteria");
    con.ConexionPostgres();

  
    String queryProducto = "SELECT * FROM producto WHERE id_producto = ?";
    try (PreparedStatement stmtProducto = con.getConnection().prepareStatement(queryProducto)) {
        stmtProducto.setInt(1, id_prod);
        ResultSet rs = stmtProducto.executeQuery();

        while (rs.next()) {
 {
                   nombre.setText(rs.getString("nombre_producto"));
                   idfamilia.setSelectedItem(String.valueOf(rs.getString("id_familia_producto")));                   
                   descripcion.setText(String.valueOf(rs.getString("descripcion_producto")));
                   precio.setText(String.valueOf(rs.getDouble("precio_producto")));
                   stock.setText(String.valueOf(rs.getInt("stock_producto")));
                   existencia.setText(String.valueOf(rs.getInt("existencia_producto")));
               }
            int id = rs.getInt("id_producto");
            java.sql.Array array = rs.getArray("id_ingrediente");
            Integer[] valores = (Integer[]) array.getArray();

           

            // Consultar ingredientes
            String queryIngrediente = "SELECT * FROM ingrediente WHERE id_ingrediente = ?";
            try (PreparedStatement stmtIngrediente = con.getConnection().prepareStatement(queryIngrediente)) {
                for (int valor : valores) {
                    stmtIngrediente.setInt(1, valor);
                    ResultSet rsl = stmtIngrediente.executeQuery();
                    while (rsl.next()) {
                        dt.addRow(new Object[]{
                        rsl.getInt("id_ingrediente"),
                        rsl.getString("nombre_ingrediente"),
                        rsl.getString("descripcion"),
                        rsl.getString("valor_nutricional")
                                
                                }); 
                    }
                    
                }
            }
        }
    }
} catch (ClassNotFoundException | SQLException | InstantiationException | IllegalAccessException ex) {
    Logger.getLogger(product.class.getName()).log(Level.SEVERE, null, ex);
}
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        try {
    String idd = buscarid.getText().trim();
    String nom = nombre.getText();
    String fam = (String) idfamilia.getSelectedItem();
    String des = descripcion.getText();
    Double val = Double.valueOf(precio.getText());
    int stc = Integer.parseInt(stock.getText());
    int exis = Integer.parseInt(existencia.getText());
    conex con = new conex("postgres","12345","localhost","5432","cafeteria");
    con.ConexionPostgres();
    String query = "UPDATE producto SET nombre_producto = ?, id_familia_producto = ?, descripcion_producto = ?, precio_producto = ?, stock_producto = ?, existencia_producto = ? WHERE id_producto = ?";
    
    try (PreparedStatement stmt = con.getConnection().prepareStatement(query)) {
        stmt.setString(1, nom);
        stmt.setString(2, fam);
        stmt.setString(3, des);
        stmt.setDouble(4, val);
        stmt.setInt(5, stc);
        stmt.setInt(6, exis);
        stmt.setInt(7, Integer.parseInt(idd));
        
        int filasAfectadas = stmt.executeUpdate();
        JOptionPane.showMessageDialog(null, "Producto Actualizado. Filas afectadas: " + filasAfectadas);
    }
    
    con.cerrar();
}        catch (SQLException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
             Logger.getLogger(product.class.getName()).log(Level.SEVERE, null, ex);
         } 

    }//GEN-LAST:event_jLabel18MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscarid;
    private javax.swing.JTextField descripcion;
    private javax.swing.JTextField existencia;
    private javax.swing.JComboBox<String> idfamilia;
    private javax.swing.JComboBox<String> idingre;
    private javax.swing.JTextField idproducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable listar;
    private javax.swing.JTable mingre;
    private javax.swing.JTable mostrar;
    private javax.swing.JTextField nombre;
    private javax.swing.JPanel panelpro;
    private javax.swing.JTextField precio;
    private javax.swing.JTextField stock;
    // End of variables declaration//GEN-END:variables
}
